#CONSTANTS FOR THE PROGRAM

#THIS IS TO ACTIVATE OR DEACTIVATE PRINT STATEMENTS
debugmode = 0

#THE SIZE OF THE WHEELS IN MM
ws = 64

#THE RPM OF THE MOTORS AT 100% POWER
rpm = 600

#HOW FAR SHOULD THE ROBOT MOVE BEFORE CHECKING FOR STAIRS IN MM
chkDst = 10

#STAIR SENSOR HEIGHT IN M
#THIS IS 6in IN M
stairSens = 0.152

#THIS IS THE WALL THRESH HOLD DISTANCE IN M
wall = 0.3